plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':api')
    implementation project(':application')
    implementation project(':domain')

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}