plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':application')
    implementation project(':domain')

    implementation 'pl.es8it.mas.contract:mas-diagnostics-api:1.0.0'
    implementation 'pl.es8it.mas.contract:mas-vehicle-api:1.0.0'

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}